version: "3.8"

services:
    webserv:
        container_name: webserv
        build:
          context: .
        network_mode: "host"
        volumes:
        - type: bind
          source: .
          target: /webserv
        # ports:
        #   - "7777:7777"
        #   - "8080:8080"


