version: "3.8"

services:
    webserv:
        container_name: webserv
        build:
          context: ./srcs
        network_mode: "host"
        environment:
            - "WEBSERV_LOGLEVEL=DEBUG" 
        volumes:
        - type: bind
          source: ./data
          target: /data
        # ports:
        #   - "7777:7777"
        #   - "8080:8080"


