print("Content-Type: text/html\r\n")
print("<html> ")
print("<head>")
print("<title> Test CGI </title>")
print("</head>")
print("<body>")
print("<center> <h1>Hello from python</h1> </center> ")
print("</body>")
print("</html>")
